# https://docs.github.com/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes

changelog:
  categories:
    # keepachangelog.com
    - title: Added
      labels:
        - release-added
    - title: Changed
      labels:
        - release-changed
    - title: Deprecated
      labels:
        - release-deprecated
    - title: Removed
      labels:
        - release-removed
    - title: Fixed
      labels:
        - release-fixed
    - title: Security
      labels:
        - release-security
    # Original categories
    - title: Documentation
      labels:
        - release-documentation
    - title: Development
      labels:
        - release-development
    - title: Dependencies
      labels:
        - dependencies
    - title: Other
      labels:
        - '*'
