version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - uv venv --python 3.13
    install:
      - uv pip install -r requirements/docs.txt
    build:
      html:
        - ./scripts/docs
