version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv run --with-requirements requirements/docs.txt -m sphinx -T -b html -d docs/_build/doctrees -D language=en docs $READTHEDOCS_OUTPUT/html
