#!/bin/bash -eux

# Build documentation with Sphinx.

uv run \
    --with-editable . \
    --with-requirements requirements/dev-docs.txt \
    --isolated \
    --no-project \
    --python 3.14 \
    sphinx-build -T -b html docs "${READTHEDOCS_OUTPUT:-docs/_build}/html"
