#!/bin/bash -eux

# Run formatting with ruff.

uv run \
    --with-requirements requirements/dev-lint.txt \
    --isolated \
    --no-project \
    ruff format

uv run \
    --with-requirements requirements/dev-lint.txt \
    --isolated \
    --no-project \
    ruff check --fix
