#!/bin/bash -eux

# Build and serve documentation with Sphinx.

uv run \
    --with-editable . \
    --with-requirements requirements/docs.txt \
    --isolated \
    --no-project \
    --python 3.13 \
    sphinx-autobuild docs docs/_build/html
